# Generated by Django 2.2.24 on 2022-12-18 15:09

from django.db import migrations
import phonenumbers


def correct_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_number):
            pure_number = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
            flat.owners_phonenumber = pure_number
            flat.save(update_fields=["owners_phonenumber"])
        else:
            flat.owners_phonenumber = None
            flat.save(update_fields=["owners_phonenumber"])



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20221213_1835'),
    ]

    operations = [
        migrations.RunPython(correct_phonenumber)
    ]
