# Generated by Django 2.2.24 on 2022-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20221218_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owner_deprecated', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
