# Generated by Django 2.2.24 on 2022-12-20 15:40

from django.db import migrations


def set_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(
            name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            number=flat.owners_phonenumber
        )
        owner.flats.set([flat])
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20221220_1840'),
    ]

    operations = [
        migrations.RunPython(set_owner),
    ]
