# Generated by Django 2.2.24 on 2023-01-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20230110_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='creator_comlaint',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_flat',
            new_name='flat',
        ),
    ]
