# Generated by Django 2.2.24 on 2023-01-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230117_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто пожаловался'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complained_flats', to='property.Flat', verbose_name='Квартира, на которую пожаловались'),
        ),
    ]
